# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 21:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200)),
                ('task', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=70)),
                ('date', models.CharField(default=datetime.date(2017, 4, 28), max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointments', models.ManyToManyField(related_name='appointments', to='first_app.User')),
                ('planned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_by', to='first_app.User')),
            ],
        ),
    ]
